version: '3.4'

services:
    proxy:
        image: traefik:v1.7.7
        ports:
            - "80:80"
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
        networks:
            - fifatrackerpublic
        labels:
            - "traefik.port=8080"
            - "traefik.frontend.rule=Host:traefik.fifatracker.localhost"
            - "traefik.docker.network=fifatrackerpublic"
            - "traefik.enable=true"
        restart: always

    web:
        image: nginx:1.15-alpine
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html:cached
            - vendor:/var/www/html/vendor:delegated
            - appcache:/var/www/html/var
        links:
            - php
        networks:
            fifatrackerpublic:
                # adding an alias because the frontend php container needs to talk to this container
                # and it will route the connection properly without putting them on the same network
                # and setting an alias
                aliases:
                    - api.fifatracker.localhost
            fifatrackerinternal:
        labels:
            - "traefik.frontend.rule=Host:api.fifatracker.localhost"
            - "traefik.port=80"
            - "traefik.docker.network=fifatrackerpublic"
            - "traefik.enable=true"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/html:cached
            - vendor:/var/www/html/vendor:delegated
            - appcache:/var/www/html/var
        networks:
            fifatrackerinternal:

    postgres:
        image: postgres:10.7-alpine
#        environment:
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: postgres
#            POSTGRES_DB: postgres
        networks:
            fifatrackerinternal:
                aliases:
                    - postgres.api.internal
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    mailhog:
        image: mailhog/mailhog
        environment:
            MH_HOSTNAME: mailhog
        networks:
            - fifatrackerinternal
            - fifatrackerpublic
        labels:
            - "traefik.frontend.rule=Host:email.fifatracker.localhost"
            - "traefik.port=8025"
            - "traefik.docker.network=fifatrackerpublic"
            - "traefik.enable=true"

networks:
    fifatrackerpublic:
        external: true
    fifatrackerinternal:

volumes:
    vendor:
    appcache:
    dbdata:
